config/routes.rb
Rails.application.routes.draw do
  resources :breweries do
    resources :brews do
      resources :ratings, :comments
    end
  end
  resources :rankings
  root 'dashboard#index'

end

app/models/brew.rb
class Brew < ActiveRecord::Base
  belongs_to :brewery
  has_many :ratings
  has_many :comments

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :brews
  validates :name, presence: true,
            length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :brew
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :brew
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  def index
    @brewery = Brewery.all
  end


  def new
    @brewery = Brewery.new
  end

  def edit
    @brewery = Brewery.find(params[:id])
  end

  def show
    @brewery = Brewery.find(params[:id])
  end

  def create
    @brewery = Brewery.new(brewery_parms)

    if @brewery.save
      redirect_to @brewery
    else
      render 'new'
    end
  end

  def update
    @brewery = Brewery.find(params[:id])

    if @brewery.update(brewery_parms)
      redirect_to @brewery
    else
      render 'edit'
    end
  end

  def destroy
    @brewery = Brewery.find(params[:id])
    @brewery.destroy

    redirect_to breweries_path
  end

  private
  def brewery_parms
    params.require(:brewery).permit(:name, :city)
  end
end

app/controllers/brews_controller.rb
class BrewsController < ApplicationController
  def index
    @brewery = Brewery.find(params[:brewery_id])
  end



  def create
    @brewery = Brewery.find(params[:brewery_id])
    @brew = @brewery.brews.create(brew_params)
    redirect_to brewery_path(@brewery)
  end

  private
  def brew_params
    params.require(:name).permit(:name, :brew_type)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def index
    sql = "SELECT AVG(r.value) AS avg, b.name AS bname, br.name AS brname, br.image FROM ratings r, brews b, breweries br
           WHERE r.brew_id = b.id
           AND b.brewery_id = br.id
           GROUP BY r.brew_id, b.name, br.name, br.image
           ORDER BY AVG(r.value) DESC
           LIMIT 10"
    @rankings  = ActiveRecord::Base.connection.execute(sql)

    sql2 = "SELECT AVG(r.value), br.name, br.image, br.id FROM ratings r, breweries br, brews b
            WHERE r.brew_id = b.id
            AND b.brewery_id = br.id
            GROUP BY br.name, br.image, br.id
            ORDER BY AVG(r.value), br.name DESC
            LIMIT 5"
    @breweries = ActiveRecord::Base.connection.execute(sql2)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    puts 'Trying to create a new Rating'
    @rating = Rating.new
  end

  def create
    puts 'Creating Rating for ' + rating_params.to_s
    rating = Rating.new(rating_params)
    rating.assign_attributes({:brew_id => params[:brew_id]})
    puts 'DRINKER => '  + rating.drinker
    @rating = rating
    if @rating.save
      redirect_to breweries_path
    else
      render 'new'
    end
  end

  private
  def rating_params
    params.require(:rating).permit(:brew_id, :value, :drinker)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


  def get_random_quote
    quotes = [
        'Beer is proof that God loves us and wants us to be happy.-Benjamin Franklin-',
        'For a quart of Ale is a meal for a King.-William Shakespeare-',
        'You can\'t be a real country unless you have a beer and an airline - it helps if you have some kind of a football team, or some nuclear weapons, but at the very least you need a beer.-Frank Zappa-',
        'He was a wise man who invented beer.-Plato-',
        ' Without question, the greatest invention in the history of mankind is beer. Oh, I grant you that the wheel was also a fine invention, but the wheel does not go nearly as well with pizza.-Dave Barry-',
        'I feel sorry for people who don\'t drink. When they wake up in the morning, That\'s as good as they\'re going to feel all day.- Frank Sinatra-',
        'An intelligent man is sometimes forced to be drunk to spend time with his fools.-Ernest Hemingway-',
        'Always do sober what you said you\'d do drunk. That will teach you to keep your mouth shut.-Ernest Hemingway-',
        'You\'re not drunk if you can lie on the floor without holding on.--Dean Martin',
        'A woman drove me to drink and I didn\'t even have the decency to thank her --W.C. Fields',
        'What contemptible scoundrel has stolen the cork to my lunch? --W.C. Fields',
        'Beauty lies in the hands of the beer holder. -Anonymous-',

        'Work is the curse of the drinking classes.-Oscar Wilde-',
        'I\'d rather have a bottle in front of me, than a frontal lobotomy -Tom Waits-',
        '24 hours in a day, 24 beers in a case. Coincidence? -Stephen Wright-',
        'Always remember that I have taken more out of alcohol than alcohol has taken out of me. -Winston Churchill-',
        'Give me a woman who loves beer and I will conquer the world. - Kaiser Wilhelm-',
        'I would kill everyone in this room for a drop of sweet beer. -Homer Simpson-',
        'Not all chemicals are bad. Without chemicals such as hydrogen and oxygen, for example, there would be no way to make water, a vital ingredient in beer. -Dave Barry-',
        'An Irishman is the only man in the world who will step over the bodies of a dozen naked women to get to a bottle of stout. -Unknown-',
        'Time is never wasted when you\'re wasted all the time. -Catherine Zandonella-',
        'Non-Drinker: a weak person who yields to the temptation of denying himself a pleasure. -Ambrose Bierce-',
        'Reality is an illusion that occurs due to lack of alcohol.-Anonymous-',


        'That\'s the problem with drinking, I thought, as I poured myself a drink. If something bad happens you drink in an attempt to forget; if something good happens you drink in order to celebrate; and if nothing happens you drink to make something happen. -Charles Bukowskoi-',
        'People who drink light \'beer\' don\'t like the taste of beer; they just like to pee alot.-Capital Brewery, Middleton, WI',
        'A fine beer may be judged with only one sip, but it\'s better to be thoroughly sure.-Czech Proverb quotes',
        'I fear the man who drinks water and so remembers this morning what the rest of us said last night.-Greek proverb quotes-',

        'All right, brain, I don\'t like you and you don\'t like me - so let\'s just do this and I\'ll get back to killing you with beer.-Homer Simpson-',
        'Alcohol, the cause and solution to all of life\'s problems.-Homer Simpson-',
        'Bart, a woman is like beer. They look good, they smell good, and you\'d step over your own mother just to get one! -Homer Simpson-',
        'I\'ve figured out an alternative to giving up my beer. Basically, we become a family of traveling acrobats.-Homer Simpson-',
        'Now son, you don\'t want to drink beer. That\'s for Daddies, and kids with fake IDs.-Homer Simpson-',
        'Beer: So much more than just a breakfast drink.-Homer Simpson-',
        'Beer... Now there\'s a temporary solution.-Homer Simpson-',
        'Apu I need a keg and a six pack to hold me until I tap the keg.-Homer Simpson-',
        'Homer no function beer well without. -Homer Simpsons',

        'Lois: Oh, my God! You can only play the piano when you\'re drunk!\\n
        Peter: Now that\'s not true! I can also vomit, fall down and make dirty calls to your sister when I\'m drunk!',
        'Lois: You\'re drunk again.  Peter: No, I\'m just exhausted \'cause I\'ve been up all night drinking.'
    ]
    return quotes.sample
  end
end

app/helpers/brew_helper.rb
module BrewHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/brewery_helper.rb
module BreweryHelper
end

app/helpers/brews_helper.rb
module BrewsHelper
end

app/helpers/concerns/breweries_helper.rb
module Concerns::BreweriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/drinker_helper.rb
module DrinkerHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/breweries/_form.html.erb
<%= form_for @brewery do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name ,class: 'form-control'%>
    </p>

    <p>
      <%= f.label :city %><br>
      <%= f.text_area :city, class: 'form-control' %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/breweries/edit.html.erb
<h1>Edit Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<div class="container">
  <% @brewery.each_slice(3) do |slice| %>
      <div class="row">
        <% slice.each do |brewery| %>
            <div class="brewery col-md-4"><%= link_to image_tag(brewery.image, :border=>0), brewery_brews_path(brewery) %></div>
        <% end %>
      </div>
  <% end %>
</div>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @brewery.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @brewery.city %>
</p>

<p>
  <Strong>Brews:</Strong>
  <ul>
    <% @brewery.brews.each do |brew| %>
        <li>
          <dt>
            Brew:
            <%= brew.name %>
            <dd>
              <strong>Type:</strong>
              <%= brew.brew_type %>
            </dd>
          </dt>
        </li>
    <% end %>
  </ul>
</p>


<p>
<h2>Add a brew:</h2>
<%= form_for([@brewery, @brewery.brews.build]) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name , class: 'form-control'%>
    </p>
    <p>
      <%= f.label :type %><br>
      <%= f.text_area :brew_type, class: 'form-control' %>
    </p>
    <p>
      <%= f.submit "Submit", class: 'btn btn-default'%>
    </p>
<% end %>
</p>

<%= link_to 'Back', breweries_path %>

app/views/brews/index.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to image_tag(@brewery.image, :border=>0), @brewery.website %><br>
    <h2>Brew Listing</h2>
  </div>

  <ul class="list-group">
    <% @brewery.brews.each do |brew| %>
        <li class="list-group-item">
          <%= link_to brew.name + ' | ' + brew.brew_type + ' | ' + brew.abv,
                      new_brewery_brew_rating_path(brew.brewery_id, brew.id),
                      class: 'panel-content' %>
        </li>

    <% end %>
  </ul>
</div>

app/views/dashboard/index.html.erb
<div id="helloExample"></div>
<br>
<br>
<script>
    var myName = $.cookie('name');
    var HelloMessage = React.createClass({displayName: "HelloMessage",
        render: function() {
            return React.createElement("h2", null, "Welcome to Brewfest, ", this.props.name, "!!!")
        }
    });
    var LoginMessage = React.createClass({displayName: "LoginMessage",
        render: function() {
            return React.createElement("h2", null, "Please Enter your Name before Rating");
        }
    })
if (myName != null){
    React.render(React.createElement(HelloMessage, {name: myName.split('::')[0]}), document.getElementById('helloExample'));
} else {
    React.render(React.createElement(LoginMessage), document.getElementById('helloExample'));
}

</script>

app/views/rankings/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2>Top 10 Ranking Beers</h2>
  </div>

  <ul class="list-group">
    <% @rankings.each do |hash| %>
        <li class="list-group-item">
          <a href="#">
              <%= hash["bname"] %><br/>
              Average Ranking: <%= hash["avg"].to_f.round(2) %> <br/>
            <%= image_tag(hash["image"], :border=>0) %>
          </a>
        </li>
    <% end %>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h2>Top 5 Breweries</h2>
  </div>

  <ul class="list-group">
    <% @breweries.each do |brewery| %>
        <li class="list-group-item">
          <%= link_to image_tag(brewery["image"], :border=>0), brewery_path(brewery["id"]) %>
        </li>
    <% end %>
  </ul>
</div>

app/views/ratings/_form.html.erb
<script>
    $(document).ready( function() {
        var drinker_name = $.cookie("name");
        if (drinker_name ==null) {
            $('#rate-btn').prop('disable', true);
            alert('Enter Name before Rating');
        } else {
            $('#rating_drinker').val(drinker_name);
        }
    })
</script>
<%= form_for( @rating, url: brewery_brew_ratings_path, class: 'form-horizontal') do |f| %>
    <div class="form-group">

      <div class="col-sm-10">
        <%= f.number_field :value, class: 'form-control', min: 1, max:10,
            placeholder: 'Rank 1-10'%>
        <%= f.hidden_field :drinker, class: 'form-control' %>
      </div>
    </div>

    <p>
      <%= f.submit "Rate", class: 'btn btn-default', id: 'rate-btn'%>
    </p>

<% end %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', brewery_brews_path(params[:brewery_id]) %>